apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akash-ci-cd  # Assuming the app name is the last part of the GitHub link
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/akash-igt/git_argo_cd
    targetRevision: HEAD
    path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
